### ISSUE TITLE
Error Deleting Sequence Question Items

### ISSUE THREAD

**Issue by jdisser** [haxwell/quizki#203]
When creating a sequence question attempting to delete an item in the list has unexpected results where more that one item is deleted.

**Comment by haxwell** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#203 - Error Deleting Sequence Question Items](https://trello.com/c/80cOGCqG/22-203-error-deleting-sequence-question-items)

**Comment by haxwell** [comment]
Fixed!
