### ISSUE TITLE
On REGISTER NEW USER page replace reCAPTCHI V1 which was shutdown 3/31/18. 

### ISSUE THREAD

**Issue by FrauDeborah** [haxwell/quizki#217]
reCAPTCHI V1 was shutdown on 3/31/18. The product was used on the REGISTER NEW USER page to validate a human was requesting a logon id.  Need to upgrade to a newer version of reCAPTCHI or find an alternative open source solution.  Currently quizki.com is approving all requests for new logon ids, including those from bots. 
![image](https://user-images.githubusercontent.com/23142096/38180191-d05e9caa-35e7-11e8-97c1-50dabc889dcd.png)

**Comment by haxwell** [comment]
https://developers.google.com/recaptcha/docs/faq For context...

**Comment by haxwell** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#217 - On REGISTER NEW USER page replace reCAPTCHI V1 which was shutdown 3/31/18.](https://trello.com/c/cQGpoqe3/27-217-on-register-new-user-page-replace-recaptchi-v1-which-was-shutdown-3-31-18)

**Comment by haxwell** [comment]
Removed the CAPTCHA. Implementing it was not as straight forward as I would have liked.. and 1) we don't have a problem with spam accounts yet, so I think we're okay for the moment, and 2) with the upgrade to Angular, we'll likely be handling this differently soon, anyway.
