### ISSUE TITLE
View Question - Edit link should not appear if the question was not created by the currently logged in user

### ISSUE THREAD

**Issue by amitlath** [haxwell/quizki#67]

**Comment by haxwell** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#67 - View Question - Edit link should not appear if the question was not created by the currently logged in user](https://trello.com/c/vprBoMBr/10-67-view-question-edit-link-should-not-appear-if-the-question-was-not-created-by-the-currently-logged-in-user)

**Comment by haxwell** [comment]
No longer an issue. Closing
